language: java
deploy:
  provider: cloudfoundry
  username: $CF_USERNAME
  password: $CF_PASSWORD
  api: $CF_API_URL
  organization: $CF_ORG
  space: $CF_SPACE
  manifest: manifest.yml       # (optional)  Defaults to manifest.yml.
  app_name: pal-tracker-upeshsai                # (optional)